import {useParams} from "react-router-dom";
import {SectionLargePadding} from "../../base/section";
import unsplash from "../../helpers/unsplash";
import {useEffect, useState} from "react";
import {Col, Container,Row} from "reactstrap";
const SingleBlog = () => {
    const{post_id} = useParams();
    console.log(post_id)
    const [singleBlogImage,onChangeSingleBlogImage] = useState([]);
    const getSingleBlogData = async term => {
        if (!post_id) return;
        const response = await unsplash.get('/photos?per_page=12&orientation=landscape', {
            params: { query: term }
        });
        onChangeSingleBlogImage(response.data[post_id-1].urls.regular);
    }
    useEffect(() => {
       getSingleBlogData()
    },[])

    return(
        <SectionLargePadding>
            <Container fluid className="singleBlogContainer">
                <Row>
                    <Col md={12}>
                        <h2 className="py-5">Blog Title {post_id}</h2>
                    </Col>
                    <Col md={12} className="blogMedia">
                        <img src={singleBlogImage} alt=""/>
                    </Col>
                    <Col md={12} className="blog-info">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cupiditate dicta doloribus nostrum odio optio, similique sint. Aliquid cupiditate dolorum eligendi exercitationem hic, inventore magnam, maiores obcaecati reprehenderit ullam vel.</p>
                    </Col>
                </Row>

            </Container>
        </SectionLargePadding>
    )
}
export default SingleBlog;